server:
  port: 9000

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**, /products/**, /login, /register
        - id: SUPPLIER-SERVICE
          uri: lb://SUPPLIER-SERVICE
          predicates:
            - Path=/api/suppliers/**, /suppliers/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowCredentials: "true"
            allowedHeaders: "*"
            allowedMethods: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: 54.179.42.252

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  app:
    version: 0.0.1
    name: Api gateway service
    description: Api gateway service