#resilience4j:
#  retry:
#    instances:
#      basic:
#        maxRetryAttemps: 3
#        waitDuration: 3s
#  ratelimiter:
#    instances:
#      basic:
#        limitForPeriod: 1
#        limitRefreshPeriod: 1s
#        timeoutDuration: 250ms


#server:
#  port: 9001
#
#spring:
#  application:
#    name: supplier-service
##
##  config:
##    import: "optional:configserver:"
##  cloud:
##    config:
##      uri: http://localhost:8888
#
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost